#pragma once

#include "../Util/StringUtil.h"

///(Internal) Handles all interactions with our Python layer
/** 
 * This internal class is the glue between the compiled Angel simulation 
 *  engine and the scripting layer generated by SWIG. 
 * 
 * The World class handles all interactions for setup and teardown; the only
 *  bit you should care about for your game code is the #ExecuteInScript 
 *  function. 
 * 
 * For more information about Python, visit http://www.python.org
 */
class PythonScriptingModule
{
public:
	/**
	 * Work the magic to set up Python and load our extension module. 
	 * 
	 * Note that the start.py file located in Scripting/EngineScripts will
	 *  get executed when this function is called. It's copied to the 
	 *  Resources/Scripts directory of all games as they're built. 
	 * 
	 * Called by the World during setup. 
	 */
	static void Initialize();
	
	/**
	 * Closes down Python. Called by the World when it's destroyed. 
	 */
	static void Finalize();
	
	/**
	 * Execute a string in the Python interpreter. Can be dangerous, but
	 *  can also make generating new interactions a lot easier. If you're 
	 *  using this function, just be careful about what you pass in. 
	 * 
	 * @param code The code to execute. 
	 */
	static void ExecuteInScript(String code);

private:
	static bool isInitialized;
};
