//////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2008-2009, Shane J. M. Liesegang
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without 
// modification, are permitted provided that the following conditions are met:
// 
//     * Redistributions of source code must retain the above copyright 
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright 
//       notice, this list of conditions and the following disclaimer in the 
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the copyright holder nor the names of any 
//       contributors may be used to endorse or promote products derived from 
//       this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE 
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
// POSSIBILITY OF SUCH DAMAGE.
//////////////////////////////////////////////////////////////////////////////

USEINPUTKEY(KEY_A,'a',"A")
USEINPUTKEY(KEY_B,'b',"B")
USEINPUTKEY(KEY_C,'c',"C")
USEINPUTKEY(KEY_D,'d',"D")
USEINPUTKEY(KEY_E,'e',"E")
USEINPUTKEY(KEY_F,'f',"F")
USEINPUTKEY(KEY_G,'g',"G")
USEINPUTKEY(KEY_H,'h',"H")
USEINPUTKEY(KEY_I,'i',"I")
USEINPUTKEY(KEY_J,'j',"J")
USEINPUTKEY(KEY_K,'k',"K")
USEINPUTKEY(KEY_L,'l',"L")
USEINPUTKEY(KEY_M,'m',"M")
USEINPUTKEY(KEY_N,'n',"N")
USEINPUTKEY(KEY_O,'o',"O")
USEINPUTKEY(KEY_P,'p',"P")
USEINPUTKEY(KEY_Q,'q',"Q")
USEINPUTKEY(KEY_R,'r',"R")
USEINPUTKEY(KEY_S,'s',"S")
USEINPUTKEY(KEY_T,'t',"T")
USEINPUTKEY(KEY_U,'u',"U")
USEINPUTKEY(KEY_V,'v',"V")
USEINPUTKEY(KEY_W,'w',"W")
USEINPUTKEY(KEY_X,'x',"X")
USEINPUTKEY(KEY_Y,'y',"Y")
USEINPUTKEY(KEY_Z,'z',"Z")
USEINPUTKEY(KEY_1,'1',"ONE")
USEINPUTKEY(KEY_2,'2',"TWO")
USEINPUTKEY(KEY_3,'3',"THREE")
USEINPUTKEY(KEY_4,'4',"FOUR")
USEINPUTKEY(KEY_5,'5',"FIVE")
USEINPUTKEY(KEY_6,'6',"SIX")
USEINPUTKEY(KEY_7,'7',"SEVEN")
USEINPUTKEY(KEY_8,'8',"EIGHT")
USEINPUTKEY(KEY_9,'9',"NINE")
USEINPUTKEY(KEY_0,'0',"ZERO")

USEINPUTKEY(KEY_MINUS,'-',"MINUS")
USEINPUTKEY(KEY_PLUS,'+',"PLUS")
USEINPUTKEY(KEY_LEFTBRACE,'[',"LEFTBRACE")
USEINPUTKEY(KEY_RIGHTBRACE,']',"RIGHTBRACE")
USEINPUTKEY(KEY_FORWARDSLASH,'\\',"FORWARDSLASH")
USEINPUTKEY(KEY_SEMICOLON,';',"SEMICOLON")
USEINPUTKEY(KEY_APOSTROPHE,'\'',"APOSTROPHE")
USEINPUTKEY(KEY_COMMA,',',"COMMA")
USEINPUTKEY(KEY_PERIOD,'.',"PERIOD")
USEINPUTKEY(KEY_BACKSLASH,'/',"BACKSLASH")
USEINPUTKEY(KEY_SPACE,' ',"SPACE")
USEINPUTKEY(KEY_DELETE, GLFW_KEY_DEL, "DELETE")
USEINPUTKEY(KEY_BACKSPACE, GLFW_KEY_BACKSPACE, "BACKSPACE")
USEINPUTKEY(KEY_LEFTARROW, GLFW_KEY_LEFT, "LEFT_ARROW")
USEINPUTKEY(KEY_RIGHTARROW, GLFW_KEY_RIGHT, "RIGHT_ARROW")
USEINPUTKEY(KEY_UPARROW, GLFW_KEY_UP, "UP_ARROW")
USEINPUTKEY(KEY_DOWNARROW, GLFW_KEY_DOWN, "DOWN_ARROW")
USEINPUTKEY(KEY_LEFTSHIFT, GLFW_KEY_LSHIFT, "L_SHIFT")
USEINPUTKEY(KEY_RIGHTSHIFT, GLFW_KEY_RSHIFT, "R_SHIFT")

// XBOX BUTTONS
USEINPUTKEY(P1BUTTON_A, 1000, "P1BUTTON_A")
USEINPUTKEY(P1BUTTON_B, 1001, "P1BUTTON_B")
USEINPUTKEY(P1BUTTON_X, 1002, "P1BUTTON_X")
USEINPUTKEY(P1BUTTON_Y, 1003, "P1BUTTON_Y")

USEINPUTKEY(P1BUTTON_START, 1004, "P1BUTTON_START")
USEINPUTKEY(P1BUTTON_BACK, 1005, "P1BUTTON_BACK")

USEINPUTKEY(P1BUTTON_LEFTTHUMB, 1006, "P1BUTTON_LEFTTHUMB")
USEINPUTKEY(P1BUTTON_RIGHTTHUMB, 1007, "P1BUTTON_RIGHTTHUMB")

USEINPUTKEY(P1BUTTON_LEFTTRIGGER, 1008, "P1BUTTON_LEFTTRIGGER")
USEINPUTKEY(P1BUTTON_RIGHTTRIGGER, 1009, "P1BUTTON_RIGHTTRIGGER")

USEINPUTKEY(P1BUTTON_LEFTBUMPER, 1010, "P1BUTTON_LEFTBUMPER")
USEINPUTKEY(P1BUTTON_RIGHTBUMPER, 1011, "P1BUTTON_RIGHTBUMPER")

USEINPUTKEY(P2BUTTON_A, 1020, "P2BUTTON_A")
USEINPUTKEY(P2BUTTON_B, 1021, "P2BUTTON_B")
USEINPUTKEY(P2BUTTON_X, 1022, "P2BUTTON_X")
USEINPUTKEY(P2BUTTON_Y, 1023, "P2BUTTON_Y")

USEINPUTKEY(P2BUTTON_START, 1024, "P2BUTTON_START")
USEINPUTKEY(P2BUTTON_BACK, 1025, "P2BUTTON_BACK")

USEINPUTKEY(P2BUTTON_LEFTTHUMB, 1026, "P2BUTTON_LEFTTHUMB")
USEINPUTKEY(P2BUTTON_RIGHTTHUMB, 1027, "P2BUTTON_RIGHTTHUMB")

USEINPUTKEY(P2BUTTON_LEFTTRIGGER, 1028, "P2BUTTON_LEFTTRIGGER")
USEINPUTKEY(P2BUTTON_RIGHTTRIGGER, 1029, "P2BUTTON_RIGHTTRIGGER")

USEINPUTKEY(P2BUTTON_LEFTBUMPER, 1030, "P2BUTTON_LEFTBUMPER")
USEINPUTKEY(P2BUTTON_RIGHTBUMPER, 1031, "P2BUTTON_RIGHTBUMPER")
